apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: remote-control-relay-frontendconfig
  labels:
    app.kubernetes.io/name: remote-control-relay
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
