apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexchat-remote-control
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pwa-deployment.yaml
  - pwa-service.yaml
  - pwa-backendconfig.yaml
  - backendconfig.yaml
  - frontendconfig.yaml
  - managedcertificate.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
