apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: remote-control-default-deny-ingress
  labels:
    app.kubernetes.io/name: remote-control-relay
spec:
  podSelector: {}
  policyTypes:
    - Ingress
