apiVersion: v1
kind: Service
metadata:
  name: remote-control-relay
  labels:
    app.kubernetes.io/name: remote-control-relay
spec:
  selector:
    app.kubernetes.io/name: remote-control-relay
  ports:
    - name: http
      port: 80
      targetPort: http
